# Generated by Django 2.1.2 on 2018-10-26 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adm',
            fields=[
                ('a_id', models.AutoField(default='1', primary_key=True, serialize=False)),
                ('ad_name', models.CharField(max_length=100)),
                ('aroll_no', models.CharField(max_length=30)),
                ('apswd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mark', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('c_id', models.AutoField(default='1', primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(default='1', primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('schedule', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('f_id', models.AutoField(default='1', primary_key=True, serialize=False)),
                ('fac_name', models.CharField(max_length=100)),
                ('froll_no', models.CharField(max_length=30, null=True)),
                ('ph_no', models.CharField(max_length=100)),
                ('course_off', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('fpswd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=30)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.course')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('no_ofdays', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='logged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='logged2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='logged3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('f_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='its.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('role_id', models.AutoField(default='1', primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('s_id', models.AutoField(default='1', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sroll_no', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=50)),
                ('spswd', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('sem_id', models.IntegerField()),
                ('cur_yos', models.IntegerField()),
                ('reg_year', models.IntegerField()),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.role')),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.IntegerField()),
                ('timeslots', models.CharField(max_length=30)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.course')),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.student'),
        ),
        migrations.AddField(
            model_name='leave',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.student'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.role'),
        ),
        migrations.AddField(
            model_name='course',
            name='f_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='its.faculty'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.student'),
        ),
        migrations.AddField(
            model_name='adm',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.role'),
        ),
    ]
