# Generated by Django 2.1.2 on 2018-10-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0002_auto_20181026_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='s_id',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
