# Generated by Django 2.1.2 on 2018-10-26 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0003_auto_20181026_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leave_roll_no', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('no_ofdays', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.student')),
            ],
        ),
    ]
