# Generated by Django 2.1.2 on 2018-10-26 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0004_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='f_id',
        ),
        migrations.AddField(
            model_name='query',
            name='a_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='its.adm'),
        ),
    ]
