# Generated by Django 2.1.2 on 2018-10-26 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0005_auto_20181026_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answerqueryadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('a_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='its.adm')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.student')),
            ],
        ),
    ]
